# Generated by Django 4.2.19 on 2025-02-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_document_file_alter_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
