# Generated by Django 4.2.19 on 2025-02-24 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_total_revenue_document_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
