# Generated by Django 4.2.19 on 2025-02-24 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_total_customers_document_uploaded_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='document',
            name='color_type',
            field=models.CharField(choices=[('color', 'Color'), ('bw', 'Black & White')], default='bw', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='double_sided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='num_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('Letter', 'Letter')], default='A4', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
