# Generated by Django 4.2.19 on 2025-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_document_num_pages_alter_document_color_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
