databases:
  - name: my-database
    plan: free

services:
  - type: web
    name: printerapp
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libcups2-dev cups gcc python3-dev
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application


  - name: printer-agent
    type: worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python printer_agent/print_manager.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
